version: 2

updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Noveum/maintainers"
    assignees:
      - "Noveum/maintainers"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    # Group minor and patch updates
    groups:
      development-dependencies:
        patterns:
          - "@types/*"
          - "@typescript-eslint/*"
          - "eslint*"
          - "prettier"
          - "vitest*"
          - "@vitest/*"
          - "typedoc"
          - "rimraf"
          - "tsup"
          - "@changesets/*"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "uuid"
          - "dotenv"
        update-types:
          - "minor"
          - "patch"
    # Ignore major version updates for stable packages
    ignore:
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      # Keep ESLint updates in sync
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "06:00"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"