name: Bug Report
description: File a bug report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us resolve the issue quickly.

  - type: input
    id: version
    attributes:
      label: Package Version
      description: What version of @noveum/trace are you running?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you running in?
      options:
        - Node.js
        - Browser
        - Serverless (AWS Lambda, Vercel, etc.)
        - Docker
        - Other
    validations:
      required: true

  - type: input
    id: node-version
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using? (if applicable)
      placeholder: e.g., 18.17.0

  - type: input
    id: framework
    attributes:
      label: Framework
      description: What framework are you using? (if applicable)
      placeholder: e.g., Express.js, Next.js, Hono

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Install @noveum/trace
        2. Create a client with configuration...
        3. Call method X...
        4. See error
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: typescript
      placeholder: |
        import { NoveumClient } from '@noveum/trace';
        
        const client = new NoveumClient({
          apiKey: 'your-api-key',
          project: 'test-project'
        });
        
        // Code that reproduces the issue...

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: Please copy and paste any relevant error output or stack traces
      render: shell
      placeholder: Paste error messages here

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Browser/platform specific
        - Network configuration
        - Related to specific features
        - Workarounds you've tried

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues that describe the same problem
          required: true
        - label: I have tried the latest version of the package
          required: true
        - label: I have included a minimal code sample that reproduces the issue
          required: true
        - label: I have provided clear steps to reproduce the issue
          required: true